# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'dnd-11th-4-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dnd-11th-4-iOS

    pod 'RxSwift', '6.7.1'
    pod 'RxCocoa', '6.7.1'
    pod 'RxGesture'
    pod 'SnapKit', '~> 5.7.0'
    pod 'Kingfisher', '~> 7.0'
    pod 'RxFlow'
    pod 'lottie-ios'
    pod 'ReactorKit'
    pod 'Alamofire'
    pod 'RxKeyboard'

    post_install do |installer|
    	installer.generated_projects.each do |project|
        	project.targets.each do |target|
            		target.build_configurations.each do |config|
                         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            	      end
        	end
     	   end
     end
end
